### ISSUE TITLE
hello,if I want to transform an ecore file to typescript code, what api should I use?

### ISSUE THREAD

**Issue by burhanxz** [crossecore/examples-java#1]

**Comment by schwichti** [comment]
CrossEcore's code generator (currently not publicly available) is able to generate TypeScript from an Ecore file. Let's say you want to generate TypeScript from MyPackage.ecore. The code generator creates a package folder with your TypeScript files. This package has a dependency to the TypeScript ecore package which is contained in the [ecore-typescript repository](https://github.com/crossecore/ecore-typescript). The ecore package is required for the reflection API and base class implementations, e.g., BasicEObjectImpl.ts. This means you need to include both mypackage and ecore in your web application. For a C# application, you would need to include [ecore-csharp](https://github.com/crossecore/ecore-csharp) and so forth.
